---

- name: "Create wordpress user"
  user:
    name: wordpress
    create_home: no
    password_lock: yes
    shell: /usr/sbin/nologin
    home: /usr/local/share/wordpress
    
- name: "Check if database already exists"
  shell: mysql wordpress --execute "EXIT"
  ignore_errors: yes
  register: wordpress_db_exists

- name: "Generate / Get wordpress DB password"
  set_fact:
    pwd_wordpress_db: "{{ lookup('password', \"{{ pwddir }}/wordpress-db chars=ascii_letters,digits,hexdigits\") }}"

- name: "Create database and set permissions"
  shell: |
    mysql --execute "CREATE DATABASE wordpress"
    mysql --execute "GRANT ALL PRIVILEGES ON databasename.* TO wordpress@localhost IDENTIFIED BY \"{{ pwd_wordpress_db }}\""
    mysql --execute "FLUSH PRIVILEGES"
  when: wordpress_db_exists.rc != 0
